version: "3"
services:
  zookeeper:
    build:
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - isolatedNetwork
    hostname: ${ZOOKEPER_HOSTNAME}
  rabbitmq:
    image: ${RABBITMQ_IMAGE_TAG}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - isolatedNetwork
    hostname: ${RABBITMQ_HOSTNAME}
  loadbalancer:
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    networks:
      - isolatedNetwork
    hostname: loadbalancer
    environment:
      - EVENT_EXCHANGE_SMOC1=${SMOC1}
      - EVENT_EXCHANGE_SMOC2=${SMOC2}
      - EVENT_EXCHANGE_SMOC3=${SMOC3}
      - EVENT_EXCHANGE_SMOC4=${SMOC4}
      - EVENT_EXCHANGE_SMOC5=${SMOC5}
      - EVENT_EXCHANGE_SMOC6=${SMOC6}
      - EVENT_EXCHANGE_SMOC7=${SMOC7}
      - EVENT_EXCHANGE_SMOC8=${SMOC8}
      - EVENT_EXCHANGE_SMOC9=${SMOC9}
      - EVENT_EXCHANGE_SMOC10=${SMOC10}
      - EVENT_EXCHANGE_SMOC11=${SMOC11}
#      - EVENT_EXCHANGE_SMOC12=${SMOC12}
#      - EVENT_EXCHANGE_SMOC13=${SMOC13}
#      - EVENT_EXCHANGE_SMOC14=${SMOC14}
#      - EVENT_EXCHANGE_SMOC15=${SMOC15}

networks:
  isolatedNetwork:
    ipam:
      driver: default
      config:
        - subnet: '192.17.41.0/24'