version: "3"
services:
  loadbalancer:
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    networks:
      - wan
    hostname: loadbalancer
    environment:
      - EVENT_EXCHANGE_SMOC1=${SMOC1}
      - EVENT_EXCHANGE_SMOC2=${SMOC2}
      - EVENT_EXCHANGE_SMOC3=${SMOC3}


networks:
  wan:
    external:
      name: distributedstatemachine_distributedWan