version: "3"
services:
  loadbalancer:
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    networks:
      - isolatedNetwork
    hostname: loadbalancer
    environment:
      - EVENT_EXCHANGE_SMOC1=${SMOC1}
      - EVENT_EXCHANGE_SMOC2=${SMOC2}
      - EVENT_EXCHANGE_SMOC3=${SMOC3}
  rabbitmq:
    image: 'rabbitmq:3.8.2-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - isolatedNetwork
    hostname: rabbitmq

networks:
  isolatedNetwork:
    ipam:
      driver: default
      config:
        - subnet: '192.17.41.0/24'